services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node build/server.js
    envVars:
      - key: NODE_ENV
        value: production
